# Generated by Django 3.1.7 on 2021-06-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210609_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryoptions',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 500.99.'}}, help_text='Maximum 500.99', max_digits=5, verbose_name='delivery price'),
        ),
    ]
